# Generated by Django 4.2.7 on 2025-07-04 19:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('room_type', models.CharField(choices=[('study_group', 'Study Group'), ('live_help', 'Live Help Session'), ('pair_programming', 'Pair Programming'), ('code_review', 'Code Review'), ('mentor_session', 'Mentor Session'), ('classroom', 'Virtual Classroom'), ('office_hours', 'Office Hours')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended'), ('scheduled', 'Scheduled')], default='active', max_length=20)),
                ('room_code', models.CharField(max_length=20, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('max_participants', models.PositiveIntegerField(default=10)),
                ('requires_approval', models.BooleanField(default=False)),
                ('allow_screen_sharing', models.BooleanField(default=True)),
                ('allow_voice_chat', models.BooleanField(default=False)),
                ('allow_file_sharing', models.BooleanField(default=True)),
                ('allow_code_execution', models.BooleanField(default=True)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('participant_count', models.PositiveIntegerField(default=0)),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.exercise')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('moderators', models.ManyToManyField(blank=True, related_name='moderated_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collaboration Room',
                'verbose_name_plural': 'Collaboration Rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedCodeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('programming_language', models.CharField(default='python', max_length=50)),
                ('current_code', models.TextField(default='')),
                ('initial_code', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_save', models.BooleanField(default=True)),
                ('execution_enabled', models.BooleanField(default=True)),
                ('edit_permissions', models.CharField(choices=[('all', 'All Participants'), ('moderators', 'Moderators Only'), ('presenter', 'Presenter Only'), ('creator', 'Creator Only')], default='all', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_sessions', to='collaboration.collaborationroom')),
            ],
            options={
                'verbose_name': 'Shared Code Session',
                'verbose_name_plural': 'Shared Code Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('debugging', 'Debugging Help'), ('concept', 'Concept Explanation'), ('code_review', 'Code Review'), ('general', 'General Question'), ('technical', 'Technical Issue')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('code_snippet', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('resolution_code', models.TextField(blank=True)),
                ('helpful_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.exercise')),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_provided', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lesson')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='collaboration.collaborationroom')),
            ],
            options={
                'verbose_name': 'Help Request',
                'verbose_name_plural': 'Help Requests',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('insert', 'Insert'), ('delete', 'Delete'), ('replace', 'Replace'), ('format', 'Format')], max_length=20)),
                ('start_line', models.PositiveIntegerField()),
                ('start_column', models.PositiveIntegerField()),
                ('end_line', models.PositiveIntegerField()),
                ('end_column', models.PositiveIntegerField()),
                ('old_text', models.TextField(blank=True)),
                ('new_text', models.TextField(blank=True)),
                ('operation_data', models.JSONField(default=dict)),
                ('version_before', models.PositiveIntegerField()),
                ('version_after', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_changes', to='collaboration.sharedcodesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code Change',
                'verbose_name_plural': 'Code Changes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('code', 'Code Snippet'), ('file', 'File Share'), ('system', 'System Message'), ('help_request', 'Help Request'), ('screen_share', 'Screen Share')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('reactions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='collaboration.chatmessage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='collaboration.collaborationroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('moderator', 'Moderator'), ('presenter', 'Presenter'), ('observer', 'Observer')], default='participant', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('kicked', 'Kicked'), ('left', 'Left')], default='active', max_length=20)),
                ('can_edit_code', models.BooleanField(default=True)),
                ('can_execute_code', models.BooleanField(default=True)),
                ('can_share_screen', models.BooleanField(default=False)),
                ('can_moderate', models.BooleanField(default=False)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('code_changes', models.PositiveIntegerField(default=0)),
                ('help_requests', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='collaboration.collaborationroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room Participant',
                'verbose_name_plural': 'Room Participants',
                'ordering': ['joined_at'],
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='collaborationroom',
            index=models.Index(fields=['room_code'], name='collaborati_room_co_5dc2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationroom',
            index=models.Index(fields=['status', 'room_type'], name='collaborati_status_c5f962_idx'),
        ),
    ]
