apiVersion: v1
kind: Namespace
metadata:
  name: wokkahlearn


---
# kubernetes/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: wokkahlearn-config
  namespace: wokkahlearn
data:
  DJANGO_SETTINGS_MODULE: "wokkahlearn.settings"
  ALLOWED_HOSTS: "wokkahlearn.com,www.wokkahlearn.com,api.wokkahlearn.com"
  CORS_ALLOWED_ORIGINS: "https://wokkahlearn.com,https://www.wokkahlearn.com"
  DEBUG: "False"